Sprint 3/step 3
AsyaCemeniel/react-burger pull request #8
Opened 2021-06-27 16:18 UTC by AsyaCemeniel

- Покрыла тестами все редьюсеры
- Написала cypress тесты для главной страницы на проверку открытия и закрытия попапа, и на dnd функциональность.

Рефакторинг по приводу беспорядка в папках , мемоизацию и написание отдельных селекторов для лучшей производительности планирую позже, как только появится время.

2021-06-28 13:21 UTC, SmilingJey requested changes
Хорошая работа, все тесты проходят, отлично, что реализован так же тест открытия и закрытия попапа, но есть несколько замечаний, которые нужно исправить:

- проект не собирается и падает с ошибкой
 Module not found: Can't resolve 'history' in '..............\src\services'
 Установите пакет history@4.7.2 в проект (другая версия может не работать)
 
- в файле ./src/components/app/index.js исправьте регистр букв
ошибка при сборке Cannot find file: 'app.jsx' does not match the corresponding name on disk: '.\src\components\app\App.jsx'.

- если пользователь при попытке перехода в личный кабинет был передресован на страницу входа, то после успешного входа должен выполнятсья переход на страницу личного кабинета, а не на главную. По заданию "Если пользователь не авторизован и пытается попасть на защищённый маршрут — его переадресовывает на маршрут /login. После авторизации пользователь автоматически переадресовывается на тот маршрут, к которому у него не получилось получить доступ ранее."

- при прямом переходе станицу защищенную авторизацией (/profile) происходит редирект на страницу входа, даже если пользователь авторизован

- если пользователь авторизирован, то у него не должно быть возможности попасть на  маршруты /login /register   /forgot-password и /reset-password.

- не должно быть нескольких тестов с одинаковым названием

2021-06-28 13:21 UTC, SmilingJey commented on src/services/reducer/user.test.js
> +  it("should set user email and name", () => {
**Надо исправить**

не должно быть нескольких тестов с одинаковым названием, сейчас 4 теста называются "should set user email and name"

2021-06-29 11:29 UTC, AsyaCemeniel commented
- Исправила одинаковые названия тестов.
- Установила пакет history@4.7.2
- добавила переадресацию на изначальный маршрут вместо главной страницы
- защитила маршруты  /login /register /forgot-password и /reset-password от авторизированных пользователей

А вот, что делать с Арр я не пойму. В моей среде разработки у меня всё в нижнем регистре, даже здесь на мастере меняла, но это не работает, каждый ревьювер говорит, что Верхний регистр. Как это исправить, если с моей стороны этого не видно?

2021-06-29 16:51 UTC, SmilingJey approved these changes
Отлично, критические ошибки исправлены, однако не забудьте оправить следующие проблемы:

- проект опять не собирается

> ./src/pages/order-page/order-page.js
> Module not found: Can't resolve 'react-router' in '\src\pages\order-page'
> 

Установите библиотеку react-router

- о том как изменить регистр букв в git посмотрите этот ресурс https://noteskeeper.ru/heritage/672/

Успехов в дальнейшем обучении!

2021-07-05 08:56 UTC, merged